### ISSUE TITLE
gulp build task failed

### ISSUE THREAD

**Issue by rkanani108** [syncfusion/ej2-samples#17]
Hi @ajithr / @SyncfusionInstall 

npm: 6.14.8
node: v12.19.0

Build failed.

C:\Users\rkanani\Documents\A\C\ej2-samples>npm run build

> @syncfusion/ej2-samples@18.3.35 build C:\Users\rkanani\Documents\A\C\ej2-samples
> gulp build

[12:20:42] Using gulpfile ~\Documents\A\C\ej2-samples\gulpfile.js
[12:20:42] Starting 'build'...
[12:20:42] Starting 'scripts'...
C:/Users/rkanani/Documents/A/C/ej2-samples/node_modules/@syncfusion/ej2-pivotview/src/pivotview/model/chartsettings-model.d.ts(1,2946): error TS2305: Module '"C:/Users/rkanani/Documents/A/C/ej2-samples/node_modules/@syncfusion/ej2-charts/index"' has no exported member 'SelectionPattern'.
[12:21:39] 'scripts' errored after 57 s
[12:21:39] TypeScript error: C:/Users/rkanani/Documents/A/C/ej2-samples/node_modules/@syncfusion/ej2-pivotview/src/pivotview/model/chartsettings-model.d.ts(1,2946): error TS2305: Module '"C:/Users/rkanani/Documents/A/C/ej2-samples/node_modules/@syncfusion/ej2-charts/index"' has no exported member 'SelectionPattern'.
    at Object.getError (C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\gulp-typescript\release\utils.js:53:15)
    at Output.getError (C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\gulp-typescript\release\output.js:224:22)
    at Output.diagnostic (C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\gulp-typescript\release\output.js:227:25)
    at ProjectCompiler.inputDone (C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\gulp-typescript\release\compiler.js:69:33)
    at CompileStream.end (C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\gulp-typescript\release\main.js:54:31)
    at DestroyableTransform.onend (C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:420:28)
    at DestroyableTransform.emit (events.js:326:22)
    at C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[12:21:39] 'build' errored after 57 s
[12:21:39] TypeScript error in plugin 'run-sequence(scripts)'
Message:
    C:/Users/rkanani/Documents/A/C/ej2-samples/node_modules/@syncfusion/ej2-pivotview/src/pivotview/model/chartsettings-model.d.ts(1,2946): error TS2305: Module '"C:/Users/rkanani/Documents/A/C/ej2-samples/node_modules/@syncfusion/ej2-charts/index"' has no exported member 'SelectionPattern'.
Details:
    diagnostic: [object Object]
    tsFile: [object Object]
    fullFilename: C:/Users/rkanani/Documents/A/C/ej2-samples/node_modules/@syncfusion/ej2-pivotview/src/pivotview/model/chartsettings-model.d.ts
    startPosition: [object Object]
    endPosition: [object Object]
Stack:
TypeScript error: C:/Users/rkanani/Documents/A/C/ej2-samples/node_modules/@syncfusion/ej2-pivotview/src/pivotview/model/chartsettings-model.d.ts(1,2946): error TS2305: Module '"C:/Users/rkanani/Documents/A/C/ej2-samples/node_modules/@syncfusion/ej2-charts/index"' has no exported member 'SelectionPattern'.
    at Object.getError (C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\gulp-typescript\release\utils.js:53:15)
    at Output.getError (C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\gulp-typescript\release\output.js:224:22)
    at Output.diagnostic (C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\gulp-typescript\release\output.js:227:25)
    at ProjectCompiler.inputDone (C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\gulp-typescript\release\compiler.js:69:33)
    at CompileStream.end (C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\gulp-typescript\release\main.js:54:31)
    at DestroyableTransform.onend (C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:420:28)
    at DestroyableTransform.emit (events.js:326:22)
    at C:\Users\rkanani\Documents\A\C\ej2-samples\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @syncfusion/ej2-samples@18.3.35 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @syncfusion/ej2-samples@18.3.35 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rkanani\AppData\Roaming\npm-cache\_logs\2020-10-23T06_51_39_912Z-debug.log

**Comment by kumaresan-subramani** [comment]
HI @rkanani108 ,


Thanks for  Contacting syncfusion.


We have resolved reported issue, please use latest Syncfusion packages.


Please let us know if you have any other concerns.
